import numpy as np
a=np.arange(60).reshape(12,5)
print(a)
print("Dimention is:")
print (a.ndim)
print("dtype name is:")
print(a.dtype)
print("itemsize is:")
print(a.itemsize)
print("type is:")
print(type(a))